## Pandas

In [14]:
import pandas as pd

In [17]:
csv_dataframe  = pd.read_csv('/Users/weichien/Desktop/Moviedata2016.csv', sep=',')

In [18]:
csv_dataframe

,Name,imdb_rating,critics_score,audience_score,critics_rating,audience_rating,best_actor_win,best_actress_win,best_dir_win
0,Suicide Squad,6.2,25,62,Rotten,Upright,no,no,no
1,Hacksaw Ridge,8.2,87,92,Certified Fresh,Upright,no,no,no
2,La La Land,8.2,93,82,Certified Fresh,Upright,no,yes,yes
3,Fantastic Beasts and Where to Find Them,7.4,73,80,Certified Fresh,Upright,no,no,no
4,Hidden Figures,7.8,93,93,Certified Fresh,Upright,no,no,no
5,Moonlight,7.5,98,80,Certified Fresh,Upright,yes,no,no
6,Deadpool,8.0,84,90,Certified Fresh,Upright,no,no,no
7,Jack Reacher,6.1,37,42,Rotten,Spilled,no,no,no
8,Keeping Up with the Joneses,5.8,19,38,Rotten,Spilled,no,no,no
9,Ghostbusters,5.3,43,53,Rotten,Spilled,no,no,no
10,Colossal,6.3,79,63,Fresh,Upright,no,no,no